version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 25
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - github.com/casbin/casbin/v2
            - github.com/cccteam
            - github.com/flowerinthenight/casbin-spanner-adapter
            - github.com/go-chi/chi/v5
            - github.com/go-playground/errors/v5
            - github.com/go-playground/validator
            - github.com/google/go-cmp/cmp
            - github.com/jackc/pgx/v5
            - github.com/pckhoi/casbin-pgx-adapter/v3
            - go.uber.org/mock/gomock
            - $gostd
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 25
    godox:
      keywords:
        - TODO
        - BUG
    lll:
      line-length: 200
    misspell:
      locale: US
    nestif:
      min-complexity: 10
    tagliatelle:
      case:
        rules:
          json: camel
        use-field-name: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .Cause(
      ignore-package-globs:
        - github.com/cccteam/httpio*
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - gochecknoinits
          - goconst
          - gocyclo
          - lll
          - mnd
          - nlreturn
          - scopelint
        path: _test\.go
      - linters:
          - gocognit
        path: migrate\.go
        text: bootstrapRoles
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
