// Code generated by MockGen. DO NOT EDIT.
// Source: ../store/store_iface.go
//
// Generated by this command:
//
//	mockgen -package access -source ../store/store_iface.go -destination ../mock_store_iface.go
//

// Package access is a generated GoMock package.
package access

import (
	context "context"
	reflect "reflect"

	store "github.com/cccteam/access/store"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CheckPermission mocks base method.
func (m *MockStore) CheckPermission(ctx context.Context, user, domain, resource, permission string) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, user, domain, resource, permission)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockStoreMockRecorder) CheckPermission(ctx, user, domain, resource, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockStore)(nil).CheckPermission), ctx, user, domain, resource, permission)
}

// CreateCondition mocks base method.
func (m *MockStore) CreateCondition(ctx context.Context, roleMapID int64, condition string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCondition", ctx, roleMapID, condition)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCondition indicates an expected call of CreateCondition.
func (mr *MockStoreMockRecorder) CreateCondition(ctx, roleMapID, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCondition", reflect.TypeOf((*MockStore)(nil).CreateCondition), ctx, roleMapID, condition)
}

// CreatePermission mocks base method.
func (m *MockStore) CreatePermission(ctx context.Context, permission *store.Permission) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermission", ctx, permission)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePermission indicates an expected call of CreatePermission.
func (mr *MockStoreMockRecorder) CreatePermission(ctx, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermission", reflect.TypeOf((*MockStore)(nil).CreatePermission), ctx, permission)
}

// CreatePermissionResourceMap mocks base method.
func (m *MockStore) CreatePermissionResourceMap(ctx context.Context, permissionID, resourceID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermissionResourceMap", ctx, permissionID, resourceID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePermissionResourceMap indicates an expected call of CreatePermissionResourceMap.
func (mr *MockStoreMockRecorder) CreatePermissionResourceMap(ctx, permissionID, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermissionResourceMap", reflect.TypeOf((*MockStore)(nil).CreatePermissionResourceMap), ctx, permissionID, resourceID)
}

// CreateResource mocks base method.
func (m *MockStore) CreateResource(ctx context.Context, resource *store.Resource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResource", ctx, resource)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResource indicates an expected call of CreateResource.
func (mr *MockStoreMockRecorder) CreateResource(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResource", reflect.TypeOf((*MockStore)(nil).CreateResource), ctx, resource)
}

// CreateRole mocks base method.
func (m *MockStore) CreateRole(ctx context.Context, role *store.Role) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, role)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockStoreMockRecorder) CreateRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockStore)(nil).CreateRole), ctx, role)
}

// CreateRoleMap mocks base method.
func (m *MockStore) CreateRoleMap(ctx context.Context, roleID, permResID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoleMap", ctx, roleID, permResID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoleMap indicates an expected call of CreateRoleMap.
func (mr *MockStoreMockRecorder) CreateRoleMap(ctx, roleID, permResID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoleMap", reflect.TypeOf((*MockStore)(nil).CreateRoleMap), ctx, roleID, permResID)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, user *store.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, user)
}

// CreateUserRoleMap mocks base method.
func (m *MockStore) CreateUserRoleMap(ctx context.Context, userID, roleID int64, domain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserRoleMap", ctx, userID, roleID, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserRoleMap indicates an expected call of CreateUserRoleMap.
func (mr *MockStoreMockRecorder) CreateUserRoleMap(ctx, userID, roleID, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserRoleMap", reflect.TypeOf((*MockStore)(nil).CreateUserRoleMap), ctx, userID, roleID, domain)
}

// DeletePermission mocks base method.
func (m *MockStore) DeletePermission(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermission", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePermission indicates an expected call of DeletePermission.
func (mr *MockStoreMockRecorder) DeletePermission(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermission", reflect.TypeOf((*MockStore)(nil).DeletePermission), ctx, name)
}

// DeleteResource mocks base method.
func (m *MockStore) DeleteResource(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResource", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResource indicates an expected call of DeleteResource.
func (mr *MockStoreMockRecorder) DeleteResource(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResource", reflect.TypeOf((*MockStore)(nil).DeleteResource), ctx, name)
}

// DeleteRole mocks base method.
func (m *MockStore) DeleteRole(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockStoreMockRecorder) DeleteRole(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockStore)(nil).DeleteRole), ctx, name)
}

// DeleteRolePermissionMap mocks base method.
func (m *MockStore) DeleteRolePermissionMap(ctx context.Context, roleID, permResID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRolePermissionMap", ctx, roleID, permResID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRolePermissionMap indicates an expected call of DeleteRolePermissionMap.
func (mr *MockStoreMockRecorder) DeleteRolePermissionMap(ctx, roleID, permResID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRolePermissionMap", reflect.TypeOf((*MockStore)(nil).DeleteRolePermissionMap), ctx, roleID, permResID)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), ctx, name)
}

// DeleteUserRoleMap mocks base method.
func (m *MockStore) DeleteUserRoleMap(ctx context.Context, userID, roleID int64, domain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserRoleMap", ctx, userID, roleID, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserRoleMap indicates an expected call of DeleteUserRoleMap.
func (mr *MockStoreMockRecorder) DeleteUserRoleMap(ctx, userID, roleID, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserRoleMap", reflect.TypeOf((*MockStore)(nil).DeleteUserRoleMap), ctx, userID, roleID, domain)
}

// ListRolePermissionResources mocks base method.
func (m *MockStore) ListRolePermissionResources(ctx context.Context, roleID, permissionID int64, domain string) ([]*store.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRolePermissionResources", ctx, roleID, permissionID, domain)
	ret0, _ := ret[0].([]*store.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRolePermissionResources indicates an expected call of ListRolePermissionResources.
func (mr *MockStoreMockRecorder) ListRolePermissionResources(ctx, roleID, permissionID, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolePermissionResources", reflect.TypeOf((*MockStore)(nil).ListRolePermissionResources), ctx, roleID, permissionID, domain)
}

// ListRolePermissions mocks base method.
func (m *MockStore) ListRolePermissions(ctx context.Context, roleID int64, domain string) ([]*store.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRolePermissions", ctx, roleID, domain)
	ret0, _ := ret[0].([]*store.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRolePermissions indicates an expected call of ListRolePermissions.
func (mr *MockStoreMockRecorder) ListRolePermissions(ctx, roleID, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolePermissions", reflect.TypeOf((*MockStore)(nil).ListRolePermissions), ctx, roleID, domain)
}

// ListRoleUsers mocks base method.
func (m *MockStore) ListRoleUsers(ctx context.Context, roleID int64, domain string) ([]*store.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoleUsers", ctx, roleID, domain)
	ret0, _ := ret[0].([]*store.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoleUsers indicates an expected call of ListRoleUsers.
func (mr *MockStoreMockRecorder) ListRoleUsers(ctx, roleID, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoleUsers", reflect.TypeOf((*MockStore)(nil).ListRoleUsers), ctx, roleID, domain)
}

// ListRoles mocks base method.
func (m *MockStore) ListRoles(ctx context.Context) ([]*store.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx)
	ret0, _ := ret[0].([]*store.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockStoreMockRecorder) ListRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockStore)(nil).ListRoles), ctx)
}

// ListUserPermissionResources mocks base method.
func (m *MockStore) ListUserPermissionResources(ctx context.Context, userID, permissionID int64, domain string) ([]*store.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserPermissionResources", ctx, userID, permissionID, domain)
	ret0, _ := ret[0].([]*store.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserPermissionResources indicates an expected call of ListUserPermissionResources.
func (mr *MockStoreMockRecorder) ListUserPermissionResources(ctx, userID, permissionID, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserPermissionResources", reflect.TypeOf((*MockStore)(nil).ListUserPermissionResources), ctx, userID, permissionID, domain)
}

// ListUserPermissions mocks base method.
func (m *MockStore) ListUserPermissions(ctx context.Context, userID int64, domain string) ([]*store.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserPermissions", ctx, userID, domain)
	ret0, _ := ret[0].([]*store.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserPermissions indicates an expected call of ListUserPermissions.
func (mr *MockStoreMockRecorder) ListUserPermissions(ctx, userID, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserPermissions", reflect.TypeOf((*MockStore)(nil).ListUserPermissions), ctx, userID, domain)
}

// ListUserRoles mocks base method.
func (m *MockStore) ListUserRoles(ctx context.Context, userID int64, domain string) ([]*store.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserRoles", ctx, userID, domain)
	ret0, _ := ret[0].([]*store.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserRoles indicates an expected call of ListUserRoles.
func (mr *MockStoreMockRecorder) ListUserRoles(ctx, userID, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserRoles", reflect.TypeOf((*MockStore)(nil).ListUserRoles), ctx, userID, domain)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(ctx context.Context) ([]*store.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]*store.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), ctx)
}

// PermissionByName mocks base method.
func (m *MockStore) PermissionByName(ctx context.Context, name string) (*store.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermissionByName", ctx, name)
	ret0, _ := ret[0].(*store.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PermissionByName indicates an expected call of PermissionByName.
func (mr *MockStoreMockRecorder) PermissionByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionByName", reflect.TypeOf((*MockStore)(nil).PermissionByName), ctx, name)
}

// ResourceByName mocks base method.
func (m *MockStore) ResourceByName(ctx context.Context, name string) (*store.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceByName", ctx, name)
	ret0, _ := ret[0].(*store.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResourceByName indicates an expected call of ResourceByName.
func (mr *MockStoreMockRecorder) ResourceByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceByName", reflect.TypeOf((*MockStore)(nil).ResourceByName), ctx, name)
}

// RoleByName mocks base method.
func (m *MockStore) RoleByName(ctx context.Context, name string) (*store.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleByName", ctx, name)
	ret0, _ := ret[0].(*store.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoleByName indicates an expected call of RoleByName.
func (mr *MockStoreMockRecorder) RoleByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleByName", reflect.TypeOf((*MockStore)(nil).RoleByName), ctx, name)
}

// UserByName mocks base method.
func (m *MockStore) UserByName(ctx context.Context, name string) (*store.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByName", ctx, name)
	ret0, _ := ret[0].(*store.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByName indicates an expected call of UserByName.
func (mr *MockStoreMockRecorder) UserByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByName", reflect.TypeOf((*MockStore)(nil).UserByName), ctx, name)
}
