CREATE TABLE Conditions (
  Id INT64 GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
  RolePermissionResourceMapId INT64 NOT NULL,
  Condition STRING(MAX) NOT NULL,
  CONSTRAINT FK_Conditions_RolePermissionResourceMaps FOREIGN KEY (RolePermissionResourceMapId) REFERENCES RolePermissionResourceMaps (Id),
) PRIMARY KEY (Id);

CREATE UNIQUE INDEX ConditionsByRolePermissionResourceMapIdAndCondition ON Conditions(RolePermissionResourceMapId, Condition);