CREATE TABLE PermissionResourceMaps (
  Id INT64 GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
  PermissionId INT64 NOT NULL,
  ResourceId INT64 NOT NULL,
  CONSTRAINT FK_PermissionResourceMaps_Permissions FOREIGN KEY (PermissionId) REFERENCES Permissions (Id),
  CONSTRAINT FK_PermissionResourceMaps_Resources FOREIGN KEY (ResourceId) REFERENCES Resources (Id),
) PRIMARY KEY (Id);

CREATE UNIQUE INDEX PermissionResourceMapsByPermissionIdAndResourceId ON PermissionResourceMaps(PermissionId, ResourceId);
