CREATE TABLE RolePermissionResourceMaps (
  Id INT64 GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
  RoleId INT64 NOT NULL,
  PermissionResourceMapId INT64 NOT NULL,
  CONSTRAINT FK_RolePermissionResourceMaps_Roles FOREIGN KEY (RoleId) REFERENCES Roles (Id),
  CONSTRAINT FK_RolePermissionResourceMaps_PermissionResourceMaps FOREIGN KEY (PermissionResourceMapId) REFERENCES PermissionResourceMaps (Id),
) PRIMARY KEY (Id);

CREATE UNIQUE INDEX RolePermissionResourceMapsByRoleIdAndPermissionResourceMapId ON RolePermissionResourceMaps(RoleId, PermissionResourceMapId);